{% set name = "pytest-cache" %}
{% set version = "1.0" %}
{% set sha256 = "be7468edd4d3d83f1e844959fd6e3fd28e77a481440a7118d430130ea31b07a9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pytest >=2.2
    - execnet >=1.1.dev1

test:
  imports:
    - pytest_cache

about:
  home: http://bitbucket.org/hpk42/pytest-cache
  license: MIT
  license_file: LICENSE
  summary: 'pytest plugin with mechanisms for caching across test runs'
  description: |
    NOTE: pytest-cache is no longer maintained since its functionality was
    integrated into pytest core starting with pytest-2.8.0.
  doc_url: http://pythonhosted.org/pytest-cache/
  doc_source_url: https://bitbucket.org/hpk42/pytest-cache/src/7875468588d60b46efd5fe3be2fa6676f6061486/doc/index.rst
  dev_url: https://bitbucket.org/hpk42/pytest-cache/

extra:
  recipe-maintainers:
    - bjodah
