travis:
  secure:
    BINSTAR_TOKEN: LMektrp3DdCWTTquXr8CM+af2PAZRtx/SCNa3nQ3ZGKZkq7FslJk19IB1FukbAlSSzWAdRfT60PD8Zb5cGgwMlTrT4glV1YEt4JEsk4pGenRpcu1tkPu4lZYol+yMtkhbMYLEscLSVYhW0snUydSLUfRCppPkBmX6RNkXtL7JiP5xW/OLPZk9dL+IK2ZyavxY+uW1XqAzVgMYvVENLT1cdDODsc2Anp8jOWj2FN875nXxF8beCb84xbAAoBIr/pACE/nOzy3CJU33T7N6sorzUnDOr4eh5V4RCsl8YoqTJYx1Jt/WQ0qaM9YbtGXjqKacS3/uz/9dhrEuKdPeJF6LXRElOEHHkVslTxP8lJ8zepQskcV0kMNkrh6CIH+Dm6c1OxrbgXem5c0U84FSKey9GbFCmGvQOoGep7g1FeSUC5rKUS9patYke80TZ/H7EosIZenkiVIUN1GRlO2HNDvJfwPRSE/2eHU5P8AOogxltqikcT2cLCV8692mcHSUzeOH2JD+Rpq8TDyk2S12nW1Hgx1GLk4TKRGgS4MMXDC+OOX2HJlINwstVirtoTpg2XuVsD7VfPRPomCMXDvWj2UIB70ut0mlF4M2DW2wJgGf5SHtl6AsqRV0flpr2oSlm64A336mXkGlerQ0Bw6ydmoTFrPLC+Qe356ZdVB+p7NqUY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
