travis:
  secure:
    BINSTAR_TOKEN: Xf71MRip3BIQdv0SbYBLNr/mYnF2woYbh93BuwqQVo8xFd+SthfXGR2VQRmmMoPuz+wbdbnoSXM7Y4lvabaduUiAcv6ijujnrCwLCZ0xDg+9fISFtVD1Yz730OeuhG4wO9ZPMVc0LvrtsEtxRtyeC6oJqQVkEUCqBz9X+SBqj/JQ9wSShypNHDnYnkWX50EnzOtZvs+kVMNlPGUT17b6WVPePTUFBGiHKGF4y4G4N1obUaI44go/qgF31FMFWPGtL1nonogmYkdla0Yl1jW4OoPmAp+IDN7JlN2sA8Ay1xGTIPD/lUpfKj8oj1wbc/vDtzfKyLa3ZZQ241BPnK6H4KMFhu9FIFCzTabV/bOqUra3JZWELRXoPvNkdWniRdWCXZsHjgfUZZ8/BmVabJBY7TJu0lycCQwpPVUmF/L19SJPvkhlLRMgQPi13A+SqVlsA/rUbslVJM51YoZEl9CBr/+y1bg3pg9NodnJFjWS0OU8bTntF9cOOG1XVCprUxWACkC4kACkYU0qRkMnoKDmMoCXFtasUReSOet+DR+qXcZMLcdSOcKYbWVxsHUSWF2oZKSrRR1oE4WqCb88Z8HJpqGtgR5l+dHeV8EHYkGPYjCLFTTaX5mzM4Dvmxs/Ov0php9aDrfvAFb3ViQdyqNlnAvv2cmPidmV4Zt3y/GMuWk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
